### ISSUE TITLE
Mocked Object runtime type

### ISSUE THREAD

**Issue by Tokenyet** [felangel/mocktail#109]
**Describe the bug**
Use the mocked object, but can't use the mocked method to another `when`. Not sure If it's related to mocktail or mockito.

**Expected behavior**
Mocked object should be used as normal object when calling the mocked method, and should be identified as the correct type of Its original return type.

**Screenshots**
(The only difference on line89 and line92,)
I want to use **rootPath** to give `fileSystem.directory` a specified argument, this is working...
![image](https://user-images.githubusercontent.com/6420527/152503142-2c34711d-ff69-4abd-9644-5dece5482707.png)

But use `rootDir.path` is not working:
![image](https://user-images.githubusercontent.com/6420527/152503315-123e8093-40d0-4245-96fe-e2ccb010f912.png)

But If I put it in variable first, then It's working...
![image](https://user-images.githubusercontent.com/6420527/152503473-cd8e2e68-0101-46a6-9724-805de8439a16.png)

The code realted to Logs.
```
13  Future<void> deleteCubeJava() async {
14    // target bin/cube_java
15    final currentDir = _fileSystem.directory(
16      join(_fileSystem.currentDirectory.path, JAVA_PORTABLE_FOLDER),
17    );
18    if (!await currentDir.exists()) return;
```

**Logs**
```
  type 'MockDirectory' is not a subtype of type 'String'
  dart:io                                            MockDirectory.path
  lib\src\duplicate_cleaner_repository.dart 16:41    DuplicateCleanerRepository.deleteCubeJava
  test\duplicate_cleaner_repository_test.dart 96:28  main.<fn>.<fn>.<fn>
  test\duplicate_cleaner_repository_test.dart 82:9   main.<fn>.<fn>.<fn>
```
`rootDir.path` was identified as `MockDirectory` instead of `String`.

**Additional context**
Not sure why, but It's really confused for me after this testing 😕

**Comment by felangel** [comment]
Hi @Tokenyet 👋 
Thanks for opening an issue!

Are you able to provide a link to a minimal reproduction sample? It would be much easier to help if I'm able to run/debug the issue locally. Thanks! 🙏
