### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by pro100svitlo** [felangel/mocktail#111]
Please update dependencies 🙏 
There are some issues that start occurring. For example:
```sh
Because freezed >=1.1.1 depends on analyzer ^3.0.0 and mocktail 0.2.0 depends on test ^1.16.0, if freezed >=1.1.1 and mocktail 0.2.0 then test_api 0.2.19 or 0.4.9.
And because mobile_app depends on flutter_test from sdk which depends on test_api 0.4.8, freezed >=1.1.1 is incompatible with mocktail 0.2.0.
So, because mobile_app depends on both freezed 1.1.1 and mocktail 0.2.0, version solving failed.
pub get failed (1; So, because mobile_app depends on both freezed 1.1.1 and mocktail 0.2.0, version solving failed.)
```

**Comment by felangel** [comment]
Hi @pro100svitlo 👋
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/3110#issuecomment-1004381832 and is due to an incompatibility between flutter test and analyzer ^3.0.0.

**Comment by pro100svitlo** [comment]
Oh, got it. 
Thanks for the fast reply and for the package it self 🙏 
Have a nice day!
