### ISSUE TITLE
Error when mocking File class

### ISSUE THREAD

**Issue by ebjorklund01** [felangel/mocktail#135]
Running into a strange bug with returning a mock of the File class. I am unit testing a method that is storing some byte data into a local file. The code that I am testing looks like the code below. The call to _fileManager.getImageFile returns a File object.

```
@override
  Future<void> addImage(
    ImageEntity image,
    Uint8List bytes,
    String userId,
  ) async {
    try {
      final imageFile = await _fileManager.getImageFile(userId, image.fileName);
      await imageFile.writeAsBytes(bytes);
    } catch (e) {
      throw IoException();
    }
  }
```

In my test file I mock the File class 

`class MockFile extends Mock implements File {}`

And stub the call to ` _fileManager.getImageFile(userId, image.fileName)` to return a MockFile.

In the test I am getting the error 

```
_TypeError (type 'Null' is not a subtype of type 'String')

#0      MockFile.path (dart:io/file.dart:563:14)
#1      ImagesLocalDataSourceImpl.addImage (package:smartlink/src/features/history/data/datasources/images_local_datasource.dart:66:44)
<asynchronous suspension>
#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>
```

If I then stub out the mocked files .path `when(() => file1.path).thenAnswer((invocation) => '');` the error goes away and the test passes as expected.

This bug obviously isn't a big deal but is unexpected behavior. I'm not sure why the file.path must be stubbed out since I am not calling that in the test or in the class I'm testing.

**Comment by felangel** [comment]
Hi @ebjorklund01 👋 
Thanks for opening an issue!

It looks like `images_local_datasource.dart:66:44` is accessing the `path` which is why it needs to be stubbed. Let me know if that helps 👍
