### ISSUE TITLE
Mocked function is not getting called instead throws type 'Null' is not a subtype of type 'Future<void>'

### ISSUE THREAD

**Issue by basti12354** [felangel/mocktail#138]
Hi,

I am having a class that handles notifications (final locator = GetIt.instance):

```
class WorkoutNotificationsCreatorAndRemover {
  WorkoutNotifications workoutNotificationsObject = WorkoutNotifications();
  NotificationRepository _notificationRepository = locator<NotificationRepository>();
  NotificationService _notificationService = locator<NotificationService>();

  WorkoutNotificationsCreatorAndRemover(this.workoutNotificationsObject);

  void createNotifications(List<Workout> allWorkouts) {
    for (int i = 0; i < allWorkouts.length; i++) {
      Workout workout = allWorkouts[i];
      scheduleNotification(workout);
      workoutNotificationsObject.listOfCreatedNotifications.add(workout.uniqueID);
    }
    _notificationRepository.saveToDB(workoutNotificationsObject);
  }

  void scheduleNotification(Workout workout) {
    _notificationService.showScheduledNotification(workout: workout);
  }
}
```

To test this class I created the following test:

```  
test('WorkoutNotifications one ITEM notifications', () {
    var notificationsRepo = MockNotificationsRepository();
    var notificationService = MockNotificationService();

    locator.registerSingleton<NotificationService>(notificationService);
    locator.registerSingleton<NotificationRepository>(notificationsRepo);

    Workout workout = TestObjects.createTestWorkoutOfTheDay();
    when(() => notificationService.showScheduledNotification(workout: workout)).thenAnswer(
            (_)  async {
          print("showScheduledNotification was called");
        }
    );
    WorkoutNotificationsCreatorAndRemover creatorAndRemover = WorkoutNotificationsCreatorAndRemover(WorkoutNotifications());
    when(() => notificationsRepo.saveToDB(creatorAndRemover.workoutNotificationsObject)).thenAnswer(
            (_)  async {
          print("saveToday was called");
          return Future<bool>.value(true);
        }
    );
    creatorAndRemover.createNotifications([TestObjects.createTestWorkoutOfTheDay()]);

    expect(creatorAndRemover.workoutNotificationsObject.listOfCreatedNotifications.length, 1);
  });
```

**Issue: print("showScheduledNotification was called"); is never called**
Instead of the mock the original method in class "NotificationService" is getting called and I am getting the "type 'Null' is not a subtype of type 'Future<void>'" error.

```
 Future<void> showScheduledNotification({required Workout workout}) async {
        _flutterLocalNotificationsPlugin.zonedSchedule(workout.uniqueID, workout.workoutName, "You have scheduled a workout today!", tz.TZDateTime.from(workout.dateOfCreation, tz.local), await _notificationDetails(),
      payload: "sarah.abs", androidAllowWhileIdle: true, uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime, );
  }
``` 

If I am using the debugger and checking my creatorAndRemover class then I can see that this instance is using my mock objects.

![image](https://user-images.githubusercontent.com/10846809/179349756-b5c5ac01-a68d-4c21-9654-7a5332aeac77.png)

What is wrong with my code? Didn't get it...

_Originally posted by @basti12354 in https://github.com/felangel/mocktail/issues/45#issuecomment-1186135594_

**Comment by felangel** [comment]
Hi @basti12354 👋
Thanks for opening an issue!

Can you please share a reproduction sample as well as the full error/stack trace? The stackTrace should point to the line of the method that isn’t being stubbed properly — it sounds like you just forgot to stub a method that is being called and returns a Future<void>.

**Comment by basti12354** [comment]
Hi @felangel,

thanks for your answer :)

I tried to create a new project with the least amount of code to share this issue with you. In the new project everything was working. 

My problem was that I was creating two different "Workout" objects. One to stub the method and another/different object to make the actual test call.

`
    Workout workout = **TestObjects.createTestWorkoutOfTheDay();**
    when(() => notificationService.showScheduledNotification(workout: workout)).thenAnswer(
            (_)  async {
          print("showScheduledNotification was called");
          return Future.value();
        }
    );
    WorkoutNotificationsCreatorAndRemover creatorAndRemover = WorkoutNotificationsCreatorAndRemover(WorkoutNotifications());
    when(() => notificationsRepo.saveToDB(creatorAndRemover.workoutNotificationsObject)).thenAnswer(
            (_)  async {
          print("saveToday was called");
          return Future<bool>.value(true);
        }
    );
    creatorAndRemover.createNotifications([**TestObjects.createTestWorkoutOfTheDay()**]);
`

**Comment by AhmedEzio47** [comment]
@basti12354 I've done exactly like you and the issue still persists, 
`   
  var defaultOfferParams = OfferParams(offerId: 'test');
   
  void arrangeUnblockOfferSuccess() {
    when(() => unblockOfferUseCase.call(defaultOfferParams))
        .thenAnswer((_) async => Right(UnblockingEntity(code: 'test')));
  }
blocTest<ActivationBloc, ActivationState>(
        'check that UnblockOfferUseCase gets called',
        setUp: () {
          arrangeUnblockOfferSuccess();
        },
        build: () => sut,
        act: (bloc) =>
            bloc.add(OfferUnblocked(offerId: defaultOfferParams.offerId)),
        verify: (_) {
          verify(() => unblockOfferUseCase.call(defaultOfferParams)).called(1);
        });`
        Are you sure this was the only change you made?
