### ISSUE TITLE
Test if a function has been called

### ISSUE THREAD

**Issue by rivella50** [felangel/mocktail#156]
Hi there,
i have the following situation: I have written a new function `void onChildrenChanged(Component component)` which i would like to test if it gets called during the process of adding a `Component` child to a `RowComponent` parent. So we have:
```
final child = Component();
final parent = RowComponent();  // extends Component
parent.add(child);
```
At the end of this add process the mentioned function `onChildrenChanged` is called in the parent with child as the parameter.
Now i wonder how i can test if this function has not been called before the add call and exactly once after the add call?
Neither mocking `Component` nor `RowComponent` would be correct i guess, since it's the function i'm interested in, and by mocking the classes the function wouldn't be called.

Normally the function `void onChildrenChanged(Component component)` would be overridden in `RowComponent`:
```
@override
void onChildrenChanged(Component component) {}
```
Can this test be created as planned?

**Comment by lukaszdebowski** [comment]
`onChildrenChanged` seems like it would notify some external listeners, looking at the name.

Assuming that is true, I would imagine you could do something like:

```
test('should call onChildrenChanged when adding new child', () {
  final child = Component();
  final parent = RowComponent();

  int callCount = 0;

  // or a different way that you listen for that callback
  parent.listenOnChildrenChanged((Component component) => callCount++);

  expect(callCount, equals(0));

  parent.add(child);

  expect(callCount, equals(1));
});
```

Or, you could also create a `TestRowComponent` which extends RowComponent and overrides the `onChildrenChanged` method like this:

```
class TestRowComponent extends RowComponent {
  ...
  
  int callCount = 0;
  
  @override
  void onChildrenChanged(Component component) {
    callCount++;
  }
}

// and then in your tests

final parent = TestRowComponent();

expect(parent.callCount, equals(0));
parent.add(child);
expect(parent.callCount, equals(1));

```

**Comment by rivella50** [comment]
Meanwhile i went for the 2nd approach which worked fine.
Thanks for your answer.
