### ISSUE TITLE
Future proofing

### ISSUE THREAD

**Issue by svarlet** [felangel/mocktail#16]
**Is your feature request related to a problem? Please describe.**
When we create a test double (stub, mock, other...) for a class which defines a method that returns a future, it is tempting to use Mocktail to return a canned future. This is a good approach to improve speed and reliability. Yet it must be arranged in a careful way to avoid complications. 

Mocktail should prohibit developers to return a canned future with `.thenReturn()`. Instead, developers should be advised to use `.thenAnswer()`. 

Indeed, as Futures don't have a "start button", they run soon after they are _instantiated_. In the context of a canned future for tests, they are unfortunately likely to complete before our production code asks for the future.

Since `await` doesn't yield/block when applied to a _completed_ future (it just unpacks the value), we write asynchronous code but run it synchronously from our tests. In short, we believe the production code is tested when we are actually testing a different program.

In my case, this led to many race conditions and an overcomplicated solution to address these race conditions.

**Describe the solution you'd like**
**My suggestion is to throw an error from within `.thenReturn()` when the argument is of type Future.** The error, may provide a brief explanation as to why it's a mistake, and a suggestion to **use `.thenAnswer()` instead.**

This is what I changed in a [fork](https://github.com/svarlet/mocktail) of your repository and have been running it successfully for a few days now. I did find that 42 out of ~150 tests were making this mistake. 

Provided that in rare cases it is perhaps desirable to return a completed Future, Mocktail could provide a distinct method to allow this, even though it should be discouraged. Perhaps the name of that method will leave no doubts?

**Describe alternatives you've considered**
None besides being careful and consistent.

**Additional context**
The docs of [SynchronousFuture](https://api.flutter.dev/flutter/foundation/SynchronousFuture-class.html) warn us but are not very well connected to your library:

> In general use of this class should be avoided as it is very difficult to debug such bimodal behavior.

I also assume that alternatives to Mocktail expose their users to a similar issue.

**Comment by felangel** [comment]
This has been addressed by #22 and is available in v0.0.2-dev 🎉

**Comment by svarlet** [comment]
Hi @felangel , 

I don't think #22 addresses it. Doing `.thenReturn(Future(() => "a value"))` is still going to schedule the future right now, and quite possibly make it complete before the stub is exercised by the production code. Then, the production code will get a completed future, thereby making it run ~asynchronously~ synchronously.

Have I missed anything? If so, can you explain?
