### ISSUE TITLE
Overhead on refactor of class

### ISSUE THREAD

**Issue by MaxAuer** [felangel/mocktail#17]
**Is your feature request related to a problem? Please describe.**
When I rename the method of a class that is mocked I have to manually update the tests. 

Lets assume this simple class:

```
abstract class A {
   B add(B object);
}
```

In a test the class would be mocked:
```
class AMock extends Mock implements A {}

void main () {
   late AMock api;

   setUp((){
      api = AMock();
   });

   test('...', () {
      final b = B();
      when(api).calls(#add).thenReturn(b.copyWith(id: 'unique_id_from_api'));
      ... test continues ...
   });
}
```

First, there is no IntelliSense for `#add` which could introduce typos. Second, if `add` would be renamed I need to manually fix the `#add` in the tests. 

**Describe the solution you'd like**
No real solution in my head right now. Just wanted to start a conversation on how to go forward with this as there is a need for an easy testing framework with null safety and besides this issue, I like the usability of mocktail!

Any thoughts on the topic?

**Comment by svarlet** [comment]
I also find that it's easy to rename a method and find breaking tests later on. Though, as I TDD, I normally find this soon after and the required change is obvious.

**Comment by felangel** [comment]
Hi @MaxAuer 👋 
Thanks for opening an issue!

This is definitely a limitation of using `Symbols` and while I'm still exploring alternative approaches it seems unlikely that we'll be able to support custom matchers while also having a type-safe API. As @svarlet mentioned the tests should fail which will be the indication to update them but I will definitely keep brainstorming possible alternatives (hence why this package is still in `dev`). If you have any suggestions, please don't hesitate to let me know, thanks! 🙏

**Comment by felangel** [comment]
Just published a type safe prerelease of mocktail 🎉

https://twitter.com/felangelov/status/1368080170695921664?s=21
