### ISSUE TITLE
when Throws Exceptions Under the Hood

### ISSUE THREAD

**Issue by MelbourneDeveloper** [felangel/mocktail#172]
**Describe the bug**
`when` causes exceptions to be thrown in the class you are mocking under the hood. You probably won't notice them if you're not debugging with the option to catch all exceptions in the debugger, but this is what happens when you turn that option on:

`TestClass`
```dart
class TestClass {
  Future<String> get hello async {
    return "Hello World";
  }
}
```

Test code:
```dart
import 'package:mocktail/mocktail.dart';
import 'package:mocktail_exceptions/shared.dart';
import 'package:test/test.dart';

class MockTestClass extends Mock implements TestClass {}

void main() {
  test('test', () async {
    var mockTestClass = MockTestClass();
    when(() => mockTestClass.hello).thenAnswer((_) async => 'Hi');
    print(await mockTestClass.hello);
  });
}
```

Result:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/16697547/207722608-558d5a14-2b63-4684-b7b6-3a4797f6983b.png">

**To Reproduce**

- Clone this [repo](https://github.com/MelbourneDeveloper/Samples)or grab the code  in the Flutter/mocktail_exceptions folder
- Open with vscode (You might be able to reproduce with Android studio, but I can't explain the steps)
- Ensure you have these debugging options turned on 
![image](https://user-images.githubusercontent.com/16697547/207723301-72bf61a5-36f7-4d33-abea-03e8d94c3f80.png)
- Debug the mocktail_test.dart test
- You will see the exception. The debugger will hit the line in `TestClass` above
- Note that this does not happen with Mockito. You can try the same thing with the mockito_test.dart. It does not throw an exception

Note: *This does not stop the test from passing. If you run either test without the debugger, it will pass.* 

**Expected behavior**
The test should not throw exceptions. The problem is that we should be able to run Dart code with the debugger turned on and never see exceptions unless something exceptional happens. The fact that the mocks throw exceptions means that we see false negatives when trying to debug.

**Screenshots**
<img width="897" alt="image" src="https://user-images.githubusercontent.com/16697547/207724519-6b9cb215-c55b-4d87-9587-8865e8a51c18.png">

**Logs**
> Analyzing mocktail_exceptions...                                        
No issues found! (ran in 1.4s)

> [✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-x64, locale en-AU)
    • Flutter version 3.3.9 on channel stable at /usr/local/Caskroom/flutter/3.0.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/christianfindlay/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

> [✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

> [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

> [✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

> [✓] VS Code (version 1.68.1)
    • VS Code at /Users/christianfindlay/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

> [✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.124

> [✓] HTTP Host Availability
    • All required HTTP hosts are available

**Additional context**
I looked through the stack trace and don't have a complete answer for why this is happening, but I suspect that mocktail is somehow partially invoking the method call. It's weird that it even cares about the class that it implements, given that the mock class does not even extend it.

**Comment by felangel** [comment]
Hi @MelbourneDeveloper 👋 
Thanks for opening an issue!

This is expected because of [how mocktail works](https://github.com/felangel/mocktail/tree/main/packages/mocktail#how-it-works). If you enable breakpoints for all exceptions you will generally have a really poor debugging experience because you will hit a breakpoint for all exceptions even when most of them are handled so I don't recommend leaving that box checked unless you really want to break on all exceptions. Hope that helps 👍

**Comment by MelbourneDeveloper** [comment]
@felangel 

Apps should not throw exceptions - caught or uncaught unless something exceptional happens. Exceptions are a way for the system to tell you something is going wrong. At the very least, exceptions eat performance. Debugging with break on all exceptions turned on is one way to detect where exceptions are occurring in your app. If you do not catch all exceptions, it's possible that exceptions will occur under the hood without detecting them. It's best practice to turn this on where possible. Incidentally, this is the most searched article on my blog:

<img width="923" alt="image" src="https://user-images.githubusercontent.com/16697547/207739754-09dd7a41-6ff4-4dfc-b8f7-9cb4ef9ecb41.png">
 
I see what you mean that, at its core, Mocktail works this way, but it should at least be acknowledged that this could cause issues for people with the debugging option turned on. It took me a while to figure out this error was occurring because of the mock configuration. It might be worth putting something explicit in the documentation about this if it's not already there.

**Comment by felangel** [comment]
> Apps should not throw exceptions - caught or uncaught unless something exceptional happens.

Exceptions can happen at any time (TimeoutException, FormatException, SocketException, etc.) and what is important is that the exceptions are caught and handled appropriately. In this case, mocktail isn’t throwing any exceptions, it is calling the closure provided, catching the resulting TypeError, and using noSuchMethod to register stubs and verify invocations.


> Debugging with break on all exceptions turned on is one way to detect where exceptions are occurring in your app. If you do not catch all exceptions, it's possible that exceptions will occur under the hood without detecting them. 

I don’t entirely agree here. There is a reason for having two different levels: one for all exceptions and one just for uncaught exceptions. Exceptions happen all the time especially in internal code (that’s why we use try/catch etc.) and it’s not an issue as long as the exceptions are caught and handled appropriately. For example, I might have some code in a library that makes an http request which times out resulting in an TimeoutException. That’s not something the developer or application is at fault for and as long as the exception is caught and handled everything is fine.

> I see what you mean that, at its core, Mocktail works this way, but it should at least be acknowledged that this could cause issues for people with the debugging option turned on. It took me a while to figure out this error was occurring because of the mock configuration. It might be worth putting something explicit in the documentation about this if it's not already there.

The “how it works section” in the readme describes this behavior but happy to review any PRs if you feel things are unclear. Thanks!

**Comment by MelbourneDeveloper** [comment]
> Exceptions happen all the time especially in internal code (that’s why we use try/catch etc.) and it’s not an issue as long as the exceptions are caught and handled appropriately.

They shouldn't happen all the time, and we should take some measures to detect them. At the very least, unwinding the stack trace is an expensive operation. 

The example you are pointing out is exactly why the debugger needs to break on all errors. If you are testing an app with debugging turned on, and you experience an unexpected `TimeoutException`, this is the exact point where you need to know that something went wrong. Otherwise, you may experience unexplained behavior in your app as you are testing. Breaking on the exception tells you that something went wrong, so you can expect different behavior. It's critical for the debugging experience.

With all that said, I totally understand that it wouldn't be possible to change this behavior. I have read the "How it works" section. My suggestion would be to add a note that tells the user that they have to turn off breaking on all exceptions in their IDE, so they don't get caught out, as I did. I can word that up into a PR if you want me to put that in the documentation.

**Comment by felangel** [comment]
> The example you are pointing out is exactly why the debugger needs to break on all errors. If you are testing an app with debugging turned on, and you experience an unexpected TimeoutException, this is the exact point where you need to know that something went wrong. Otherwise, you may experience unexplained behavior in your app as you are testing. Breaking on the exception tells you that something went wrong, so you can expect different behavior. It's critical for the debugging experience.

My point was that this is only an issue if the exception is uncaught. If it was caught then that presumably means the exception was accounted for.

> My suggestion would be to add a note that tells the user that they have to turn off breaking on all exceptions in their IDE, so they don't get caught out, as I did. I can word that up into a PR if you want me to put that in the documentation.

Sounds great, thanks!

**Comment by MelbourneDeveloper** [comment]
> My point was that this is only an issue if the exception is uncaught. If it was caught then that presumably means the exception was accounted for.

Not true. Years of experience have shown me that suppressed exceptions very often cover up code design issues. Wrapping a try/catch around something that throws exceptions is often a band-aid for replacing a faulty API, or dealing with the underlying cause. Most importantly, unnecessary exceptions derail the actual purpose of exceptions: to report the existence of something going wrong in the system. The debugging experience is the lightning rod for picking up these issues. Exceptions should smack you in the face 👊🏼.

> Sounds great, thanks!

I will word something up.

**Comment by MelbourneDeveloper** [comment]
@felangel closing this for now, but I still intend on submitting a PR for the documentation when I have time. Incidentally, I just realized it's possible to cause this same issue if you attempt to use Mockito Mocks as fakes.
