### ISSUE TITLE
Mocked riverpod '*Notifier' has no instance method '_setElement' on Flutter 3.7.0 (Dart 2.19.0)

### ISSUE THREAD

**Issue by kmcgill88** [felangel/mocktail#181]
I have been using mocktail with riverpod to mock `AsyncNotifier`, among other notifiers. When using Flutter 3.3.10 (Dart 2.18.6) the example project widget tests work as expected. Upgrading to Flutter 3.7.0 (Dart 2.19.0) all tests fail with 

```
═╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AsyncCounterAutoDispose(dirty, dependencies:
[UncontrolledProviderScope], state: _ConsumerState#40f2d):
Class 'MockAsyncIntsAutoDispose' has no instance method '_setElement'.
Receiver: Instance of 'MockAsyncIntsAutoDispose'
Tried calling: _setElement(Instance of
'AutoDisposeAsyncNotifierProviderElement<AsyncIntsAutoDispose, int>')
```

**To Reproduce**
1. Clone [example project](https://gitlab.com/kmcgill88/riverpod_mocktail_examples)
2. `flutter --version`, confirm you are on Flutter 3.3.10 (flutter downgrade if needed)
3. `flutter test`
4. All tests pass
5. `flutter upgrade`, confirm you are on flutter 3.7.0
6. `flutter test`
7. Tests fail

**Expected behavior**
Mocks to work on all versions of Flutter.

**Logs **
```
783084@CASEYSMAC riverpod_mocktail_examples % flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-x64, locale en-US)
    • Flutter version 3.7.0 on channel stable at /Users/783084/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/783084/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Users/783084/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/783084/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8617.8

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/783084/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.8214.16

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/783084/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danielmahon** [comment]
`mockito` also seems to fail with the same error
FYI @rrousselGit

**Comment by rrousselGit** [comment]
```dart
class FooMock extends Notifier with Mock implements Foo {}
```

**Comment by kmcgill88** [comment]
Continuing with the example project, extending `Notifier` gave me a compiler error.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/1992370/215267635-34bffd83-a3be-40d6-8380-f0f3d7bda664.png">

I attempted to implement the overrides but I'm not fully understanding how to handle `NotifierProviderRef<AsyncValue<int>> get ref =>` 

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/1992370/215268214-77c783f1-29ee-457d-85bf-9ba68c298ae0.png">

Even if these overrides worked I really was hoping for a simple `class FooMock extends Notifier with Mock implements Foo {}` like I'm accustomed to.

**Comment by rrousselGit** [comment]
You use an AsyncNotifier not a Notifier. So subclass that instead

**Comment by kmcgill88** [comment]
@rrousselGit  ah, my bad. I tried to have an example of both. 

`class MockAsyncIntsAutoDispose extends AsyncNotifier with Mock implements AsyncIntsAutoDispose {}`

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1992370/215268884-7eb240ed-1362-4f0c-be0a-607b055299de.png">

@rrousselGit is your expectation these should be manually overridden? The message makes sense since I'm extending `AsyncNotifier` but I don't want to implement and manually override everything. There has to be a simpler way. I ran into this same dilemma using mockito.

**Comment by rrousselGit** [comment]
You need to specify the generic type on AsyncNotifier too

**Comment by kmcgill88** [comment]
Adding the type cut down the compiler errors but still isn't valid. Thanks for your patience. I feel helpless here.
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1992370/215272339-96387935-5f62-4428-a941-206c1ac802c2.png">

I shouldn't have to implement anything, right?

**Comment by rrousselGit** [comment]
You didn't subclass AsyncNotifier in your notifier. You subclassed AutoDisposeAsyncNotifier
So subclass that in your mock too :)

**Comment by kmcgill88** [comment]
doh! 🤦🏻‍♂️ I have really struggled with this. I think I get the pattern now.

What has thrown me off is `AsyncIntsAutoDispose` already extends `AutoDisposeAsyncNotifier<int>` so it feels like I'm duplicating when the mock extends `AutoDisposeAsyncNotifier<int>` as well.
```dart
// class MockAsyncIntsAutoDispose extends Mock implements AsyncIntsAutoDispose {} <-- dont do this!
class MockAsyncIntsAutoDispose extends AutoDisposeAsyncNotifier<int> with Mock implements AsyncIntsAutoDispose {}
```

```dart
// class MockAsyncIntsKeepAlive extends Mock implements AsyncIntsKeepAlive {} <-- dont do this!
class MockAsyncIntsKeepAlive extends AsyncNotifier<int> with Mock implements AsyncIntsKeepAlive {}

// class MockAsyncIntsAutoDispose extends Mock implements AsyncIntsAutoDispose {} <-- dont do this!
class MockAsyncIntsAutoDispose extends AutoDisposeAsyncNotifier<int> with Mock implements AsyncIntsAutoDispose {}

// class MockTestNotifier extends Mock implements TestNotifier {} <-- wrong!
class MockTestNotifier extends StateNotifier<int> with Mock implements TestNotifier {
  MockTestNotifier(super.state);
}
```

I've updated the example project and everything is working! I am still curious why just extending Mock worked pre Flutter 3.7.0. Thanks again for your help!

**Comment by danielmahon** [comment]
On a similar note, with 3.7.0 I am also now getting a warning about stubbing the `build` method:
`The member 'build' can only be used for overriding.dart[invalid_use_of_visible_for_overriding_member](https://dart.dev/diagnostics/invalid_use_of_visible_for_overriding_member)`
```dart
    class MockManageNotificationsController extends AutoDisposeNotifier<ManageNotificationsState>
      with Mock
      implements ManageNotificationsController {}

    late MockManageNotificationsController mockManageNotificationsController;

    setUp(() async {
      mockManageNotificationsController = MockManageNotificationsController();
      // The member 'build' can only be used for overriding.dart[invalid_use_of_visible_for_overriding_member](https://dart.dev/diagnostics/invalid_use_of_visible_for_overriding_member)
      when(() => mockManageNotificationsController.build())
          .thenAnswer((_) => ManageNotificationsState(areEnabled: true));
      when(() => mockManageNotificationsController.onSettingsButtonPressed()).thenAnswer((_) async => {});
    });

**Comment by felangel** [comment]
Closing this for now since it appears the original question was resolved and the discussions are specific to riverpod and not mocktail.
