### ISSUE TITLE
Dependencies causing issues DCM action

### ISSUE THREAD

**Issue by GroovinChip** [felangel/mocktail#187]
**Describe the bug**
Apparently, the DCM action [cannot pull dependencies](https://github.com/GroovinChip/macos_ui/actions/runs/4153938021/jobs/7185925668#step:4:27) due to mocktail's dependencies being behind DCM's. I find these kinds of errors quite difficult to read, so I'm hoping someone here can confirm that this is indeed the issue (I filed an [issue](https://github.com/dart-code-checker/dart-code-metrics-action/issues/163) with DCM, it's been a week with nothing).

**To Reproduce**
This only happens when I run the DCM action on my [PR](https://github.com/GroovinChip/macos_ui/pull/342/), which is difficult to replicate unless you fork my repo and run a dummy PR on it to match what I currently have up. I'm reluctant to advise going through that process, but that's the best way I can think of to reproduce. 

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/4250470/218287683-7854e0d5-7076-49de-ac76-20f71401b8ce.png)

**Logs**
Already linked above.

> Paste the output of running `flutter doctor -v` here.
N/A since the issue is with a GitHub action. DCM works fine as part of my project itself.

**Additional context**
N/A other than it is worth noting I've tried several times to pin specific versions of dependencies that are noted in the action log, with no success. But again, I've always found such errors difficult to decipher properly. I'm really just going off the summary of the log, which reads ` So, because macos_ui depends on both dart_code_metrics ^5.5.1 and mocktail ^0.3.0, version solving failed.` 🤷

**Comment by felangel** [comment]
Hey @GroovinChip 👋
I can take a closer look shortly but my immediate thought is your GitHub workflow is using an older version of Flutter. Can you confirm that your PR checks are running using the latest stable version of Flutter? Thanks!

**Comment by GroovinChip** [comment]
Hi @felangel! I can confirm that my workflow is using the latest stable version of Flutter - see [here](https://github.com/GroovinChip/macos_ui/blob/dev/.github/workflows/flutter_analysis.yml#L13).

**Comment by GroovinChip** [comment]
Resolved! I was using an older version of the action. Embarrassing!!

**Comment by felangel** [comment]
> Resolved! I was using an older version of the action. Embarrassing!!
Glad you figured it out! 🎉
