### ISSUE TITLE
Incompatible with dart_metrics_code

### ISSUE THREAD

**Issue by LucasMatheusDev** [felangel/mocktail#188]
**Describe the bug**
When trying to add dart_metrics_code in my pubspec there is a dependency compatibility error.

**To Reproduce**
Add dart_code_metrics: ^5.3.0 to your pubspec.yaml
d screenshots to help explain your problem.

**Logs **
Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 <1.21.2 depends on test_api 0.4.9, test >=1.16.0-nullsafety.19 <1.21.2 requires analyzer >=1.0.0 <3.0.0 or test_api 0.2.19 or 0.4.9.
And because test >=1.21.0 <1.21.6 depends on analyzer >=2.0.0 <5.0.0 and test >=1.21.6 <1.21.7 depends on test_api 0.4.14, test >=1.16.0-nullsafety.19 <1.21.7 requires analyzer >=1.0.0 <5.0.0 or test_api 0.2.19 or 0.4.9 or 0.4.14.
And because test >=1.21.7 <1.22.0 depends on test_api 0.4.15 and test >=1.22.0 <1.22.1 depends on test_api 0.4.16, test >=1.16.0-nullsafety.19 <1.22.1 requires analyzer >=1.0.0 <5.0.0 or test_api 0.2.19 or 0.4.9 or 0.4.14 or 0.4.15 or 0.4.16.
And because test >=1.22.1 <1.22.2 depends on test_api 0.4.17 and test >=1.22.2 depends on test_api 0.4.18, test >=1.16.0-nullsafety.19 requires test_api 0.2.19 or 0.4.9 or 0.4.14 or 0.4.15 or 0.4.16 or 0.4.17 or 0.4.18 or analyzer >=1.0.0 <5.0.0.
Because dart_code_metrics >=5.5.0 depends on analyzer >=5.1.0 <5.5.0 and dart_code_metrics >=5.2.0 <5.5.0 depends on analyzer >=5.1.0 <5.4.0, dart_code_metrics >=5.2.0 requires analyzer >=5.1.0 <5.5.0.
Thus, if dart_code_metrics >=5.2.0 and test >=1.16.0-nullsafety.19 then test_api 0.2.19 or 0.4.9 or 0.4.14 or 0.4.15 or 0.4.16 or 0.4.17 or 0.4.18.
And because mocktail >=0.1.3 depends on test ^1.16.0, if dart_code_metrics >=5.2.0 and mocktail >=0.1.3 then test_api 0.2.19 or 0.4.9 or 0.4.14 or 0.4.15 or 0.4.16 or 0.4.17 or 0.4.18.
And because metrics_example depends on flutter_test from sdk which depends on test_api 0.4.12, dart_code_metrics >=5.2.0 is incompatible with mocktail >=0.1.3.
So, because metrics_example depends on both dart_code_metrics ^5.3.0 and mocktail ^0.3.0, version solving failed.
pub get failed (1; So, because metrics_example depends on both dart_code_metrics ^5.3.0 and mocktail ^0.3.0, version solving failed.)

**ScreenShot**
![Captura de tela 2023-02-13 155213](https://user-images.githubusercontent.com/81427844/218548369-c240a605-45a1-45d4-99cf-9d7a780fe0bc.png)

**Comment by LucasMatheusDev** [comment]
Is there a possibility to change the version of the `test`dependency so that it is possible to use dart_metrics_code?

**Comment by LucasMatheusDev** [comment]
@felangel Thanks for answering me, I'm using : Flutter 3.3.10 and  Dart 2.18.6. 

to use dart_metrics only in flutter version 3.7 ? 

> Oi@LucasMatheusDev 👋 Obrigado por abrir um problema!
> 
> Acredito que isso deva ser resolvido na última versão estável do Flutter/Dart. Você pode verificar se está testando isso no Flutter 3.7 e no Dart 2.19?

**Comment by felangel** [comment]
> @felangel Thanks for answering me, I'm using : Flutter 3.3.10 and Dart 2.18.6.
> 
> to use dart_metrics only in flutter version 3.7 ?
> 
> > Oi@LucasMatheusDev 👋 Obrigado por abrir um problema!
> > Acredito que isso deva ser resolvido na última versão estável do Flutter/Dart. Você pode verificar se está testando isso no Flutter 3.7 e no Dart 2.19?

This was a bug in Flutter -- see https://github.com/flutter/flutter/issues/115284.

**Comment by LucasMatheusDev** [comment]
> > @felangelObrigado por me responder, estou usando: Flutter 3.3.10 e Dart 2.18.6.
> > usar dart_metrics apenas na versão 3.7 do flutter?
> > > Oi@LucasMatheusDev👋Obrigado por abrir um problema! 
> > > Acredito que isso deva ser resolvido na última versão estável do Flutter/Dart. Você pode verificar se está testando isso no Flutter 3.7 e no Dart 2.19?
> 
> Este foi um bug no Flutter -- consulte [flutter/flutter#115284](https://github.com/flutter/flutter/issues/115284) e #152 .

Thank you for helping me, this issue is not valid I will close it
