### ISSUE TITLE
Unit Test type 'Null' is not a subtype of type 'Future<ApiResponse<TokenModel, TokenErrors>>'

### ISSUE THREAD

**Issue by TheGlorySaint** [felangel/mocktail#189]
**Describe the bug**
Running my Unit Test for the signin cubit, throws me following error: `type 'Null' is not a subtype of type 'Future<ApiResponse<TokenModel, TokenErrors>>'`.

I have the signin cubit, an authentication repository and an apiclient. In the SigninCubit function login, I call the authentication cubit, with the login function that Returns an APIResponse with an Tokenmodel and an Tokenerrors. Inside the authentication function login, i call the apiclient, that calls the api.

**To Reproduce**
I have created a minimal viable Product https://github.com/TheGlorySaint/Bloc_Test_Repo to test this issue.

1. Go to test/presentation/intro/cubit/intro_cubit_cubit_test.dart
2. Run the first test in the login group

I have disabled the breakpoint to catch all exceptions, as i had read that in a post.

**Logs **

flutter doctor -v                     
[✓] Flutter (Channel master, 3.8.0-12.0.pre.50, on macOS 13.2.1 22D68 darwin-arm64, locale de-DE)
    • Flutter version 3.8.0-12.0.pre.50 on channel master at /opt/homebrew/Caskroom/flutter/3.7.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6a94f25a9d (vor 2 Stunden), 2023-02-14 02:22:14 -0500
    • Engine revision 17ab09d382
    • Dart version 3.0.0 (build 3.0.0-233.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/blackbox/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 110.0.5481.96

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by ejdrian313** [comment]
Is explained in error description...

A test tried to use `any` or `captureAny` on a parameter of type `$T`, but
registerFallbackValue was not previously called to register a fallback value for `$T`.

To fix, do:

```
void main() {
  setUpAll(() {
    registerFallbackValue(/* create a dummy instance of `$T` */);
  });
}
```
in your case:
```
class ApiResponseFake extends Fake implements ApiResponse{}

void main() {
  setUpAll(() {
    registerFallbackValue(ApiResponseFake());
  });
}
```
This instance of `$T` will only be passed around, but never be interacted with.
Therefore, if `$T` is a function, it does not have to return a valid object and
could throw unconditionally.
If you cannot easily create an instance of `$T`, consider defining a `Fake`:

```
class MyTypeFake extends Fake implements MyType {}

void main() {
  setUpAll(() {
    registerFallbackValue(MyTypeFake());
  });
}
```

Fallbacks are required because mocktail has to know of a valid `$T` to prevent
TypeErrors from being thrown in Dart's sound null safe mode, while still
providing a convenient syntax.
