### ISSUE TITLE
How to Mock a State?

### ISSUE THREAD

**Issue by jassirr** [felangel/mocktail#223]
**Describe the bug**

**To Reproduce**

State MyState extends Equatable {

int value;

void getValue() {
  return state.value;
}

}
class MyBloc extends Bloc<MyEvent,MyState> {
   MyBloc() : super(MyState()) {

   }

  someFunction(event, emitter) {
 emit(state.copyWith(status: status.loading));
   int value = state.getValue();
}

}

**Expected behavior**
I want to mock this getValue function in my State class to in blocTest

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

**Additional context**

**Comment by felangel** [comment]
You can use seed in blocTest to set the bloc’s state to whatever you like before adding events. Hope that helps!
