### ISSUE TITLE
Repository.updateItem() Function Throws Null Subtype Exception in Bloc Test Event

### ISSUE THREAD

**Issue by dipu0** [felangel/mocktail#225]
**Describe the bug**
When utilizing the bloc test to act an event that triggers the execution of the following code snippet:

`bool? isDone = await repository!.updateItem(newList);`

where the updateItem function is defined as:

```
Future<bool?> updateItem(List<entity?> entityList) async {
  // Implementation details...
}
```
An exception is thrown during execution, specifically: "type 'Null' is not a subtype of type 'Future<bool?>'".

**To Reproduce**

1. Invoke the bloc test with the relevant event triggering the code mentioned above.
2. Observe the execution and the thrown exception.

**Expected behavior**
The updateItem function should handle the provided list (newList), perform its operations, and return a Future<bool?> based on the operation's success or failure.

**Actual Behavior**
The code execution results in an exception: "type 'Null' is not a subtype of type 'Future<bool?>'", which is unexpected and indicates an issue within the function or its invocation.

**Comment by felangel** [comment]
Hi @dipu0 👋
Can you share a link to a minimal reproduction sample? I’m guessing you’re using a mock bloc and not stubbing updateItem but if your goal is to test the bloc you shouldn’t be mocking it in the first place. Hope that helps!

**Comment by dipu0** [comment]
Yes, i am mocking but a repository, and **updateItem** is method of that repo, i need just a true from that method return, so in setUp i have set both the 

```
setUp: () {
      when(() => mockRepository.getCartItemList()).thenAnswer(
            (_) async => [
          ItemEntity(
               //--------
          ),
        ],
      );
      when(() => mockRepository.updateCartItem(any())).thenAnswer((_) async => true);
    },
```
eventually this solve my previous problem but Now i am facing new problem which is

When I call two events one after another, here I have called **'get items'** then I have **decremented** the count of it. In my case, I am using a single state class using **copyWith**. Here, the state remains when not updating anything, but the decrement is working after getting data. After that, I am decrementing, but in the actual output, it shows the item count is decremented from the beginning.

Expected: [
            ItemState:ItemState(CallbackStatus.loading, null, 0.0),

            ItemState:ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 2}], 20.0),

            ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 2}], 20.0),

            ItemState:ItemState(CallbackStatus.loading, [ItemEntity{id: 1, brandId: null, productName: Product 1, brandName: null, packingUnit: null, discountedPrice: 10.00, cartItemCount: 2}], 20.0),

            ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 10.0)
          ]
  Actual: [
            ItemState:ItemState(CallbackStatus.loading, null, 0.0),

            ItemState:ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, productImage: null, productCategory: null, categoryId: null, cartItemCount: 1}], 20.0),
            ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, brandId: null, productName: Product 1, brandName: null, packingUnit: null, sellingUnit: null, packSize: null, price: null, discountedPrice: 10.00, categoryId: null, cartItemCount: 1}], 20.0),
            ItemState:ItemState(CallbackStatus.loading, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 20.0),
            ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 10.0)
          ]
   Which: at location [1] is ItemState:<ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 20.0)> instead of ItemState:<ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 2}], 20.0)>

==== diff ========================================

[ItemState(CallbackStatus.loading, null, 0.0),
ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: [-2-]{+1+}}], 20.0),
ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: [-2-]{+1+}}], 20.0), 
ItemState(CallbackStatus.loading, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: [-2-]{+1+}}], 20.0), 
ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 10.0)]

==== end diff ====================================

here cartitemCount goes 2 to 1 from the begining but it should not.
