### ISSUE TITLE
captureAny list order differs in release mode

### ISSUE THREAD

**Issue by brianneal-wf** [felangel/mocktail#229]
**Describe the bug**

We have a large set of unit tests that we converted from `mockito` to `mocktail`. One thing we noticed was the verification result list order was different when the test was run in release mode. The same test under `mockito` would pass in both DDC and release modes.

**To Reproduce**

We have some code like this:

```
          final captured = verify(() => myMock.myMethod(
                position1,
                position2,
                named1: 'foo',
                named2: 'bar',
                a: captureAny(named: 'a'),
                b: captureAny(named: 'b'),
                c: captureAny(named: 'c'),
              )).captured;
```

**Expected behavior**

Under `mockito` `captured` is, in both DDC and release modes, in the order `a, b, c`.

Under `mocktail` `captured` is in the above order in DDC mode but the order is different when the tests are compiled in release mode (from memory I think it was `c, a, b`).

Just curious if this is intentional and we can't count on the order or if this is a bug?

**Comment by felangel** [comment]
Hi @brianneal-wf 👋 
Thanks for opening an issue!

I'll try to see if I can reproduce this locally but in the meantime if you can provide a reproduction sample and the steps you're taking the run the test, I'd greatly appreciate it, thanks!

**Comment by brianneal-wf** [comment]
@felangel Sorry I should have tried that before opening the issue. I created a sample app locally with a test that mirrors our real test but the issue does not reproduce. We are thinking it might be related to optimization levels in use, but really have no idea. You can probably close this issue for now.

BTW, thank you so much for `mocktail` we are very excited to use it and to avoid the generation times of `mockito`.

**Comment by felangel** [comment]
> @felangel Sorry I should have tried that before opening the issue. I created a sample app locally with a test that mirrors our real test but the issue does not reproduce. We are thinking it might be related to optimization levels in use, but really have no idea. You can probably close this issue for now.
> 
> BTW, thank you so much for `mocktail` we are very excited to use it and to avoid the generation times of `mockito`.

No worries at all! Really appreciate the kind words and please let me know if you're able to reproduce this and I'm more than happy to take a closer look 👍

**Comment by dustyholmes-wf** [comment]
Generally, when wanting to capture a parameter, we do this because we want to inspect a more complicated object. 

Another way to perform this operation
```dart
    final captured = verify(() => myMock.myMethod(
                position1,
                position2,
                named1: 'foo',
                named2: 'bar',
                a: captureAny(named: 'a'),
                b: captureAny(named: 'b'),
                c: captureAny(named: 'c'),
              )).captured;

    final a = captured[0] as Map<String, bool>;
    expect(a, containsPair('mykey', false));
```

is using a `that:` parameter. 

```dart
    final captured = verify(() => myMock.myMethod(
                position1,
                position2,
                named1: 'foo',
                named2: 'bar',
                a: any(
                      named: 'a',
                      that: allOf(
                        isA<Map<String, bool>>(),
                        hasLength(1),
                        containsPair('mykey', false),
                      ),
                ),
                b: captureAny(named: 'b'),
                c: captureAny(named: 'c'),
              )).captured;

    final a = captured[0] as Map<String, bool>;
    expect(a, containsPair('mykey', false));
```

**Comment by lauracallahan-wk** [comment]
👋 We're also running into this problem. If you split up the expectations into separate tests to validate the captured field is correct, it works. But if you try to evaluate multiple `captureAny` fields, they come through in a different order in release vs ddc/dev mode.

Example:

```
final captured = verify(() => foo.bar(SomeObject, any(), captureAny(), vanilla: captureAny(named: 'vanilla'), chocolate: captureAny(named: 'chocolate')).captured;

expect(captured.first(), 'content');
expect(captured[1](), 'vanilla');
expect(captured[2](), 'chocolate');
```

In dart2js, I'm seeing `chocolate` come through first. In ddc, I see vanilla come through first, as expected. 

Of note is that the named fields are coming through in alphabetical order, which may or may not be a red herring. 

Unfortunately @dustyholmes-wf's workaround doesn't work for us, because the attributes we're trying to introspect are functions.

```
SomeObject(vanilla: () => 'vanilla', chocolate: () => 'chocolate');
```

**Comment by felangel** [comment]
@lauracallahan-wk are you able to provide a link to a minimal reproduction sample? Thanks!

**Comment by lauracallahan-wk** [comment]
@felangel Sure thing!

```
class IceCream {
  IceCream();

  void addScoop(String flavor,
      {Function()? hasSprinkles, Function()? hasFudge}) {
  }
}
```

with test

```
test('ice cream', () async {
          MockIceCream iceCream = MockIceCream();
          iceCream.addScoop(
            'vanilla',
            hasSprinkles: () => true,
            hasFudge: () => false,
          );
          final captured = verify(() => iceCream.addScoop('vanilla',
              hasSprinkles: captureAny(named: 'hasSprinkles'),
              hasFudge: captureAny(named: 'hasFudge'))).captured;
          expect(captured.first(), isTrue);
          expect(captured[1](), isFalse);
        });
```

fails in dart2js but passes in DDC

**Comment by felangel** [comment]
> [@felangel](https://github.com/felangel) Sure thing!
> 
> ```
> class IceCream {
>   IceCream();
> 
>   void addScoop(String flavor,
>       {Function()? hasSprinkles, Function()? hasFudge}) {
>   }
> }
> ```
> 
> with test
> 
> ```
> test('ice cream', () async {
>           MockIceCream iceCream = MockIceCream();
>           iceCream.addScoop(
>             'vanilla',
>             hasSprinkles: () => true,
>             hasFudge: () => false,
>           );
>           final captured = verify(() => iceCream.addScoop('vanilla',
>               hasSprinkles: captureAny(named: 'hasSprinkles'),
>               hasFudge: captureAny(named: 'hasFudge'))).captured;
>           expect(captured.first(), isTrue);
>           expect(captured[1](), isFalse);
>         });
> ```
> 
> fails in dart2js but passes in DDC

Can you share the commands you’re using to compile and run with dart2js as well as the dart version you’re using? Thanks!

**Comment by lauracallahan-wk** [comment]
@felangel Just wanted to check in on this 🙂

**Comment by felangel** [comment]
> [@felangel](https://github.com/felangel) Just wanted to check in on this 🙂

Sorry for the delayed response! Can you elaborate on the previous message? It'd be super helpful if you could provide me the link to a GitHub repo that contains a minimal reproduction sample?

**Comment by lauracallahan-wk** [comment]
@felangel Sure, what additional details do you need? I don't have a repo where I can show this to you, but the [example I previously posted ](https://github.com/felangel/mocktail/issues/229#issuecomment-2749312585) would work just by dropping it into any Dart repo.

**Comment by felangel** [comment]
> [@felangel](https://github.com/felangel) Sure, what additional details do you need? I don't have a repo where I can show this to you, but the [example I previously posted ](https://github.com/felangel/mocktail/issues/229#issuecomment-2749312585) would work just by dropping it into any Dart repo.

Can you provide a minimal pubspec.yaml with the dependencies you’re using? Since you’re running build_runner it’d be helpful to see the dependencies you’re using.

**Comment by lauracallahan-wk** [comment]
@felangel  Here you go:
```
name: name
version: version
description: A set of examples

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # public dependencies
  intl: ^0.18.1
  logging: ^1.2.0
  meta: ^1.16.0
  opentracing: ^1.0.11
  over_react: ^5.4.3
  redux: ^5.0.0
  uuid: ^4.2.2

dev_dependencies:
  # public dependencies
  build_runner: ^2.3.3
  build_test: ^2.2.1
  build_web_compilers: '>=3.2.7 <5.0.0'
  dart_dev: ^4.2.3
  dependency_validator: ^3.2.3
```

**Comment by felangel** [comment]
@lauracallahan-wk I took a closer look and wasn't able to reproduce when using `dart compile js` with the latest stable version of Dart. This looks like it was just a bug in dart2js which is now deprecated. Are you able to upgrade to Dart 3 and re-test?

**Comment by lauracallahan-wk** [comment]
@felangel Unfortunately we're unable to upgrade to Dart 3 at this time. We're in the process of migrating packages to be compatible, but aren't fully there yet.
