### ISSUE TITLE
Add mock for Extension types

### ISSUE THREAD

**Issue by nullskill** [felangel/mocktail#244]
As I can see there's no way by design for mocktail to mock recently added Extension types?

It would be nice to have such feature. Is there any possibility?

**Comment by xShuusui** [comment]
I am also battling with this a while, as it is really annoying. There was an issue about it a few years ago: https://github.com/felangel/mocktail/issues/58.

@felangel Is there anything new regarding this?

**Comment by felangel** [comment]
This is a limitation of the way extensions are implemented afaik. When you write an extension, it’s similar to adding a static method which isn’t possible to mock. Not sure there’s anything we can do in mocktail to improve this but I’m open to suggestions.

**Comment by xShuusui** [comment]
Thanks for the quick answer, I didn’t realize extensions worked that way. It makes more sense now why they can’t be mocked.

**Comment by felangel** [comment]
Closing this for now but happy to continue the conversation if anyone has suggestions.
