### ISSUE TITLE
How to mock method that returns type implementing `Future`?

### ISSUE THREAD

**Issue by ChopinDavid** [felangel/mocktail#251]
**Describe the bug**
I am trying to mock a method that returns a type that implements `Future`. I have so far attempted this in 4 ways:

- When using `when(() => myMock.myMethod()).thenReturn(MockOfTypeImplementingFuture())` the tests build but I am getting the expected "Invalid argument(s): `thenReturn` should not be used to return a Future. Instead, use `thenAnswer((_) => future)`." error.
- When using `thenAnswer` via `when(() => myMock.myMethod()).thenAnswer((_) async => MockOfTypeImplementingFuture())` I have a build error: "The argument type 'Future<T> Function(Invocation)' can't be assigned to the parameter type 'Answer<MockOfTypeImplementingFuture>'".
- When using `thenAnswer` via `when(() => myMock.myMethod()).thenAnswer((_) => MockOfTypeImplementingFuture())` (note the absence of `async`) I get the runtime error: "type 'Null' is not a subtype of type 'Future<dynamic>'".
- When using `thenAnswer` via `when(() => myMock.myMethod()).thenAnswer((_) => MockOfTypeImplementingFuture())` while also overriding `then` to return `Future.value()` in `MockOfTypeImplementingFuture`, the test hangs indefinitely.

**To Reproduce**
I attempt to remedy this by using  `when(() => myMock.myMethod()).thenAnswer((_) => MockOfTypeImplementingFuture())`, which utilizes `thenAnswer` without having a build error. But then I get the following runtime error: "type 'Null' is not a subtype of type 'Future<dynamic>'".

1. Clone [ChopinDavid/mocktail_bug](https://github.com/ChopinDavid/mocktail_bug)
2. Run `flutter pub get`
3. Open `test/widget_test.dart`
4. Run "when using when.thenAnswer" and see that the test hangs indefinitely
5. Uncomment the `then` override in the `MockBar` class, located at `lib/bar.dart`
6. Notice that we now get the "type 'Null' is not a subtype of type 'Future<dynamic>'" runtime error
7. Notice that the "when using when.thenAnswer with `async`" test does not even build when line 30 is uncommented
8. Notice that running the "when using when.thenReturn" test gives the "Invalid argument(s): `thenReturn` should not be used to return a Future. Instead, use `thenAnswer((_) => future)`." runtime error

**Additional context**
For context, I am wondering how to mock a method that returns a class implementing `Future` because I am trying to mock Firebase Storage's [`Reference`](https://firebase.google.com/docs/storage/flutter/create-reference#create_a_reference)'s [`putFile`](https://firebase.google.com/docs/storage/flutter/upload-files#upload_from_a_file) method, which returns an `UploadTask`, which ultimately implements `Future.`

**_Basically, this issue could be resolved if anybody could pull down the repo I had made and get one of the tests to pass while mocking `mockFoo.getBar()`!_** I assume that overriding `then` in `MockBar` makes sense, but I am not sure what value to return to have the test hang indefinitely.

See more:
- [Firebase Storage `Reference` source code](https://github.com/firebase/flutterfire/blob/07eb25fa67a8c7c3e21275bacd234641721de8fc/packages/firebase_storage/firebase_storage/lib/src/reference.dart#L4)
- [`Reference.putFile` source code](https://github.com/firebase/flutterfire/blob/07eb25fa67a8c7c3e21275bacd234641721de8fc/packages/firebase_storage/firebase_storage/lib/src/reference.dart#L126-L129)
- [`UploadTask` class source code](https://github.com/firebase/flutterfire/blob/07eb25fa67a8c7c3e21275bacd234641721de8fc/packages/firebase_storage/firebase_storage/lib/src/task.dart#L88)

**Comment by RomanTruba-Teya** [comment]
You're on the right way, you just need to avoid `MockOfTypeImplementingFuture`. Answer with the future result instead.
This should work:
`when(() => myMock.myMethod()).thenAnswer((_) async => MockOfTypeImplementingResult())`

**Comment by felangel** [comment]
Closing for now but feel free to file a new issue if this is still a problem, thanks! 🙏
