### ISSUE TITLE
feat: improve `registerFallbackValue` error messaging

### ISSUE THREAD

**Issue by felangel** [felangel/mocktail#41]
@felangel  The example provided by @Amir-P above shows the issue. This sequence

```dart
...
group('description', () {
    MockOtherTestClass otherTestClass = MockOtherTestClass();
    when(() => otherTestClass.test(any())).thenReturn('expected');
    test('test', () {
...
```
will continue to tell you to add a `setup` that calls `registerFallbackValue` even after you add the recommended code.

The only way to make it work is to move the `when` into the `test`
```dart
...
group('description', () {
    MockOtherTestClass otherTestClass = MockOtherTestClass();
    test('test', () {
        when(() => otherTestClass.test(any())).thenReturn('expected');
...
```

_Originally posted by @rich-j in https://github.com/felangel/mocktail/issues/40#issuecomment-814425894_

**Comment by Albert221** [comment]
Hi! I just stumbled upon the:

```
Bad state: A test tried to use `any` or `captureAny` on a parameter of type `UserState`, but
registerFallbackValue was not previously called to register a fallback value for `UserState`

To fix, do:

\```
void main() {
  setUpAll(() {
    registerFallbackValue<UserState>(UserState());
  });
}
\```

If you cannot easily create an instance of UserState, consider defining a `Fake`:

\```
class UserStateFake extends Fake implements UserState {}

void main() {
  setUpAll(() {
    registerFallbackValue<UserState>(UserStateFake());
  });
}
\```
```

I thought that my use case and/or thought process will help you improve the error message.

I am using both `mockito` and `bloc_test` in my tests, but I have import on `mocktail` (aliased `mocktail`) in my test file where I need mocked cubit. I have this code:

```dart
BlocProvider<UserCubit>(create: (_) {
  final mock = MockUserCubit();
  mocktail
      .when(() => mock.state)
      .thenReturn(UserState.loadSuccess(user0));
  return mock;
}),
```

This is what I'd do in Mockito. But this throws the error above. I'm not sure why does this happen nor why do I need to call this `registerFallbackValue`.

**Comment by felangel** [comment]
Hi @Albert221 👋 
Sorry for the inconvenience! This is currently working as expected as described in https://github.com/felangel/mocktail/issues/42#issuecomment-815875700. Let me know if that helps 👍

**Comment by felangel** [comment]
Closing this because this is working as expected. In the above example, `when` is evaluated before `setUpAll` which means that `registerFallbackValue` hasn't been called yet. In general, I don't recommend using `when` outside of `setUp` or `test` because it will likely result in unexpected behavior since that code will be evaluated prior to any test setup or execution.
