### ISSUE TITLE
[Not A Bug]: How to stub inner callbacks / closure?

### ISSUE THREAD

**Issue by TheOneAndOnlyGarcia** [felangel/mocktail#50]
Hello! 

i am trying to mock the following method of sqlite_api.dart by (https://pub.dev/packages/sqflite):
```dart
Future<T> transaction<T>(Future<T> Function(Transaction txn) action, {bool? exclusive});
```

my implementation/adapting of the method is like:
```dart
Future<void> _transaction(Set<DatabaseLocalRequest> payload) async {
    await this._api.transaction((txn) async => {
      for (final req in payload) {
        await txn.rawInsert(req.query.sql, req.query.arguments)
      }
    });
}
```

my db_test.dart using Mocktail (https://pub.dev/packages/mocktail):
```dart
class MockDb extends Mock implements Database {}
...
test('if [single] put succeeds', () async {
      // SETUP
      sut = DatabaseLocalProvider(db: mockDb);
      final query = Statement(sql: 'INSERT INTO Test(name, value, num) VALUES("some name", 1234, 456.789)');
      final req = DatabaseLocalRequest(query: query);

      // MOCK
      when(() => mockDb.transaction((txn) => txn.rawInsert(req.query.sql, req.query.arguments)))
          .thenAnswer((_) async => 1);

      // ACT, ASSERT
      await sut.put(req: req, bulkReq: null).then((response) => {
        expect(response, ...
      });
}); // test end
```

I got the following response from the console **ERROR**:
🚨🚨 
```console
type 'Null' is not a subtype of type 'Future<Set<Set<int>>>'
```

----------

How do I stub the inner `txn.rawInsert()` method that should respond with the `Future<Set<Set<int>>>` with `{{1}}`?

Thanks in advance!

**Comment by Ascenio** [comment]
I don't think there's a way to mock that callback because it's a implementation detail and in the `when` part the callback you provided as an argument is different from the one your code use. In this case you might just use this:
```dart
when(() => mockDb.transaction(any())).thenAnswer((_) async => 1);
```

**Comment by TheOneAndOnlyGarcia** [comment]
> I don't think there's a way to mock that callback. It's a implementation detail, so the callback you provided in `when` part is different from the one your code passes to `_transaction`, hence the Null result. In this case you might just use this:
> 
> ```dart
> when(() => mockDb.transaction(any())).thenAnswer((_) async => 1);
> ```

it can be so simple! thank you

**Comment by felangel** [comment]
Thanks @Ascenio for taking the time to help out! 🙏
Closing for now since it seems there is no further action required 👍
