### ISSUE TITLE
Why is there no built-in fallback value for DateTime?

### ISSUE THREAD

**Issue by samandmoore** [felangel/mocktail#52]
**Describe the bug**
I wrote a test that used a mock with a method accepting a `DateTime` and I got the error that I need to register a fallback value for `DateTime`.

**Expected behavior**
I was expecting that there'd be a fallback value already registered since `DateTime` is a commonly used built-in type. 

I'm curious what you think!

Cheers

**Comment by felangel** [comment]
Hey @samandmoore 👋 
Thanks for opening an issue!

Yeah that's a good call. I think it makes sense to have a built-in fallback for `DateTime` since it's part of `dart:core` 👍 
I can add it shortly, thanks!

**Comment by felangel** [comment]
Should be fixed now as part of v0.1.4 🎉

**Comment by samandmoore** [comment]
Amazing. Thanks a lot!
