### ISSUE TITLE
 we can't define a stub on an object that we want to mock before constructing it, but the constructor for the mock prevents us from stubbing the public member

### ISSUE THREAD

**Issue by VladimirCimbora** [felangel/mocktail#55]
```
DiagnosticsScreenBloc({
    required this.myDiagnosticsListBloc,
  }) : super(DiagnosticsScreenState.initialize()) {
    myDiagnosticsListSubscription = myDiagnosticsListBloc.stream.listen(
      (state) {
        // some code
    );
    
```
    This is how constructor of tested class looks like.
    
     setUp(
    () {
      myDiagnosticsListBloc = MockMyDiagnosticsListBloc();

      when(() => myDiagnosticsListBloc.stream).thenAnswer(
        (_) => Stream<MyDiagnosticsListState>.fromIterable([]),
      );

      diagnosticsScreenBloc = DiagnosticsScreenBloc(
        myDiagnosticsListBloc: myDiagnosticsListBloc,

      );

    },
  );
  
  Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?
  LateInitializationError: Local 'diagnosticsScreenBloc' has not been initialized.

  Those are the errors I get when I try to run the tests.
  
  If i remove this when from setup I get this error
  type 'Null' is not a subtype of type 'Stream<MyDiagnosticsListState>' in type cast

This is how I generate mock for MyDiagnosticsListBloc

```
@GenerateMocks([
], customMocks: [
  MockSpec<MyDiagnosticsListBloc>(returnNullOnMissingStub: true),
])
```

Is there any way you can help me solve this ?

**Comment by felangel** [comment]
Hi @VladimirCimbora 👋
Thanks for opening an issue!

Can you please share a minimal reproduction sample so that I can run your test locally? Thanks 🙏

**Comment by VladimirCimbora** [comment]
Hi @felangel I don't think I can simply extract some piece of our code :/ The problem is that everything was working before we migrate to null-safety after that we are getting those errors and it is related to DiagnosticsScreenBloc constructor and that we are trying to reach that stream

**Comment by VladimirCimbora** [comment]
Hi @felangel I created a reproduction sample for you. 
https://github.com/VladimirCimbora/mockito_test

**Comment by felangel** [comment]
> Hi @felangel I created a reproduction sample for you.
> https://github.com/VladimirCimbora/mockito_test

Thanks! I noticed you’re using mocktail and mockito together. Can you explain why? If you’re already using mocktail I recommend removing mockito.
