### ISSUE TITLE
'Null' is not a subtype of type 'Future<void>'

### ISSUE THREAD

**Issue by srockytfl** [felangel/mocktail#56]
Hi, I'm migrating some app to null safety and I found this package to be easier to use than mockito, but now I'm having this issue:
'Null' is not a subtype of type 'Future<void>'

I have this abstract class:
import 'dart:async';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

abstract class Prefs {

  Future<String> getString(String key);

  Future<void> setString(String key, String s);
}
// the implementation
class SecureStoragePrefs implements Prefs {
  static final storage = new FlutterSecureStorage();

  Future<String> getString(String key) async {
    String? value = await storage.read(key: key);
    return value ?? "";
  }

  Future<void> setString(String key, String s) async {
     storage.write(key: key, value: s);
  }
}

My viewmodel:

class LogoutViewModel {
  Prefs prefs;

  LogoutViewModel(this.prefs);

  Future<void> logout() async {
    await prefs.setString("user.prefs", "");
  }
}

And the test:

`import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockPrefs extends Mock implements Prefs {}

void main() {

  late LogoutViewModel logoutViewModel;
  late Prefs prefs;

  setUp(() {
    prefs = MockPrefs();
    logoutViewModel = new LogoutViewModel(prefs);
  });

  testWidgets('should clear all user data', (WidgetTester tester) async {
    logoutViewModel.logout();

    verify(() => prefs.setString("user.prefs", ""));
  });
}`

Since prefs.setStrig returns Future<void>, why am I receiving this error?

**Comment by felangel** [comment]
Hi @srockytfl 👋 
Thanks for opening an issue!

This is because you're not stubbing the `setString` call (so it's returning `Null` instead of `Future<void>`):

```dart
testWidgets('should clear all user data', (WidgetTester tester) async {
    when(() => prefs.setString(any(), any())).thenAnswer((_) async => {});
    
    logoutViewModel.logout();

    verify(() => prefs.setString("user.prefs", ""));
});
```

The above snippet should work, hope that helps 👍
