### ISSUE TITLE
Invalid implementation override when using Fake with ThemeData and ColorScheme

### ISSUE THREAD

**Issue by zeshuaro** [felangel/mocktail#59]
**Describe the bug**
When using `Fake` with `ThemeData` and `ColorScheme`, I'm getting an `invalid_implementation_override` error with the following message:

```
'Object.toString' ('String Function()') isn't a valid concrete implementation of 'Diagnosticable.toString' ('String Function({DiagnosticLevel minLevel})')
```

**To Reproduce**

```dart
class FakeThemeData extends Fake implements ThemeData {}

class FakeColorScheme extends Fake implements ColorScheme {}
```

**Expected behavior**
I should be able to use `Fake` with `ThemeData` and `ColorScheme`

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
N/A

**Comment by felangel** [comment]
Hi @zeshuaro 👋 
Thanks for opening an issue!

This is because `ThemeData` and `ColorScheme` have a different `toString` function signatures. You can define a mixin to address the issue:

```dart
mixin DiagnosticableToStringMixin on Object {
  @override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
    return super.toString();
  }
}

class FakeThemeData extends Fake
    with DiagnosticableToStringMixin
    implements ThemeData {}
```

Hope that helps 👍

**Comment by zeshuaro** [comment]
Thanks @felangel, your example works perfectly. Would be nice to have this documented somewhere 👍
