### ISSUE TITLE
How to mock Future<void>function({Rect? bounds}) ?

### ISSUE THREAD

**Issue by Wizzel1** [felangel/mocktail#64]
**Describe the bug**
I am trying to verify that a method on a viewModel gets called on button tap but I am getting an error.

The original method looks like this : 

`Future<void> exportNotes({Rect? bounds}) {}`

I have tried to mock it like this : 
`when(() => _vmMock.exportNotes()).thenAnswer((_) => Future.value());`

and then run the following test :

```
testWidgets('calls exportNotes if button is pressed', (tester) async {
          await _pumpAssessmentDetailsCard(tester);
          await tester.pumpAndSettle();

          final exportButtonTextFinder = find.text('Export Notes');
          final exportButtonFinder = find.ancestor(
              of: exportButtonTextFinder,
              matching:
                  find.byWidgetPredicate((widget) => widget is OutlinedButton));

          expect(exportButtonFinder, findsOneWidget);

          await tester.tap(exportButtonFinder);
          verify(() => _vmMock.exportNotes()).called(1);

          tester.idle();
        });
```

So the button exists but when the tester runs .tap()  I am getting an error 

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _TypeError was thrown running a test:
type 'Null' is not a subtype of type 'Future<void>'
```

**Expected behavior**
I was expecting to get a verification of the executed method

**Logs **
No issues found! (ran in 3.2s)

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by mattsolle-sf** [comment]
Should be `exportNotes(any(named: 'bounds'))`

**Comment by Wizzel1** [comment]
Thanks 😊
