### ISSUE TITLE
Add support for type arguments matching

### ISSUE THREAD

**Issue by renancaraujo** [felangel/mocktail#66]
**Is your feature request related to a problem? Please describe.**

On a scenario where we have a mocked instance with methods that receive type arguments, proceedings like `verify` never take notice of type arguments,

```dart
// real calls
stub.someMethodWithTypeArgs<SomeType>()
stub.someMethodWithTypeArgs<SomeAnotherType>()

// verify call
final result = verify(() => stub.someMethodWithTypeArgs<SomeType>());

print(result.callCount); // will be 2, even though we are verifying inly for calls passing `SomeType`. 
```

**Describe the solution you'd like**
Take type arguments into consideration as much as positional and named arguments. 

**Describe alternatives you've considered**
We could evolve to have Type Matchers like `Any` but probably not for the current state of the support of type arguments on dart. 
```dart
verify(() => stub.someMethodWithTypeArgs<Any>());
```

**Additional context**
The fix would be probably be added [here](https://github.com/felangel/mocktail/blob/main/packages/mocktail/lib/src/_invocation_matcher.dart#L56).

**Comment by renancaraujo** [comment]
Added a PR for this: #67

**Comment by felangel** [comment]
Related to https://github.com/dart-lang/mockito/issues/155

**Comment by felangel** [comment]
@shilangyu you'd need to write a stub for each type you want to mock
