### ISSUE TITLE
Add ArgThat Function

### ISSUE THREAD

**Issue by supposedlysam-bb** [felangel/mocktail#68]
**Is your feature request related to a problem? Please describe.**
I'm replacing Mockito with Mocktail and would like to use the same (or similar) way of testing that we already do.

**Describe the solution you'd like**
Please see Mockito's [docs](https://pub.dev/documentation/mockito/latest/mockito/argThat.html) and the [commit](https://github.com/dart-lang/mockito/commit/aa9e03b437c4a7cf66e41d5bd33d8dfc2375be19) that added this function

**Describe alternatives you've considered**
I'm open to alternative ways of writing this, but thought I'd see if it was of interest here.

**Additional context**
We have some tests where we've created our own custom matchers to be used with Mockito's `argThat` function. 

Most of our tests are checking type equality this way though:
```dart
// Mockito syntax
verify(graphQLDataSource.query(
        argThat(isA<CafesByKeywordQuery>()),
    )).called(1);
```

**Comment by felangel** [comment]
Hi @supposedlysam-bb 👋
Thanks for opening an issue!

You should be able to use any(that: …)

```dart
// mocktail syntax
verify(graphQLDataSource.query(
        any(that: isA<CafesByKeywordQuery>()),
    )).called(1);
```

Let me know if that helps 👍

**Comment by supposedlysam-bb** [comment]
This is perfect, thank you!
