### ISSUE TITLE
How to pass arguments to mock constructor + mock internal method or work around it

### ISSUE THREAD

**Issue by Albertbol** [felangel/mocktail#69]
**Describe the bug**
Mocked constructor is not taking arguments and I cannot mock internal methods if using a real class with mocked repository passed in the constructor.

**To Reproduce**
First of all, thank you for the great plugin, this is not even a bug more like a question probably and help for a workaround if it's not fixable directly.

I have a class that takes repository in constructor argument because I have all 3rd party connections there I want to pass it as a mock to stub everything, but first of all Mock class does not care about constructor and I simply cannot pass to it arguments or override it, I can use real class and pass mock repository its fine, but what if I want to additionally mock other methods of this class because it's not extending mock I am not able to mock another internal method and fake class will ask for a lot of code duplications.

```dart
import 'package:mocktail/mocktail.dart';
// I removed some types to just show the point
// A Real Cat class
class Cat {
  final repositoryClassThatNeedsToBeMocked; // should be mocked
  Cat(this.repositoryClassThatNeedsToBeMocked); // want to pass mocked repository
  
  functionForTest() {
      repositoryClassThatNeedsToBeMocked.someFunctionWhichIWantToMock(); // should be mocked
      /* 
        some logic that I want to test...
      */
      heavyInternalFunctionToMock(); // should be mocked
   };

   heavyInternalFunctionToMock() => {}; // i want to mock it also 
}

// A Mock Cat class
class MockCat extends Mock implements Cat {} // here besides constructor is required and needs repositoryClassThatNeedsToBeMocked, he is not asking for it and override is not working either.
```

**Expected behavior**
Not sure how complex it is to integrate arguments in the mocked constructor but it will solve a lot of issues and make design clear, otherwise maybe some kind of spy implementation, etc, or design workaround tips are appreciated

**Comment by felangel** [comment]
Hi @Albertbol 👋 
Thanks for opening an issue!

If you're trying to write unit tests for the `Cat` class then you shouldn't create a `MockCat` instead you should create a `MockRepository` and inject the `MockRepository` into the real `Cat`:

```dart
class MockRepository extends Mock implements Repository {}

void main() {
  test('...', () {
    final repository = MockRepository();
    final cat = Cat(repository);
    
    // Stub methods on repository
    when(() => repository.foo()).thenReturn(...);

    // Interact with cat instance
    expect(cat.bar, equals(expected));
  });
}
```

Hope that helps 👍

**Comment by Albertbol** [comment]
Hey, thanks a lot for spending some time and answering.

I tried this method previously, but I faced a problem: I cannot stub methods of **Cat** class.
I have some methods which use other methods from Cat and I would like to just stub them.

```dart
class Cat {
  final repository;
  Cat(this.repository);

  bar() {
  // some logic that I want to test
  foo(); // foo call that I want to stub
  }

  foo() {
  // some heavy logic here... that I want to stub and avoid
  }
}

class MockRepository extends Mock implements Repository {}

void main() {
  test('...', () {
    final repository = MockRepository();
    final cat = Cat(repository);
    
    // Stub methods on repository
    when(() => repository.foo()).thenReturn(...);

    // Interact with cat instance
    expect(cat.bar, equals(expected));
  });
}
```

**Comment by felangel** [comment]
@Albertbol no problem! I really don't recommend that approach. If you want to fully test a class you should use a real implementation of that class and only mock its dependencies.

**Comment by Albertbol** [comment]
Ok thanks, I just wanted to make sure that I did not miss some other strategy.
Thanks again!
