### ISSUE TITLE
Support using `Mock` as mixin

### ISSUE THREAD

**Issue by raffomania** [felangel/mocktail#73]
**Is your feature request related to a problem? Please describe.**
I'm using mocktail in conjunction with getx and want do use the `Mock` class as a mixin:

```dart
class MockBluetoothService extends GetxService
    with Mock
    implements BluetoothService {}
```

However, the [prefer_mixin](https://dart-lang.github.io/linter/lints/prefer_mixin.html) rule tells me that `Mock` should be a `mixin`, not a `class`. I've disabled the rule for now.

**Describe the solution you'd like**
It would be awesome if `mocktail` provided a `MockMixin` or similar that was tailor-made to be used as a mixin.

**Describe alternatives you've considered**
Alternatives are to disable the `prefer_mixin` rule. I don't think I can use `GetxService` as a mixin.

**Comment by felangel** [comment]
Closing for now since it's been a while and it doesn't appear there are any actionable next steps. Feel free to comment if you have any further questions and I'm happy to continue the conversation 👍

**Comment by raffomania** [comment]
Thanks for the response, I didn't get around to testing it but assume that your answer will indeed fix my problem.

**Comment by tazik561** [comment]
In my situation, I want to mock mixing class generated by Riverpod:

`class MockNewUser extends _$Reviews with Mock implements Reviews {}
`
I am getting this error : **Mixin can only be applied to class.**
