### ISSUE TITLE
Default, common use stubs

### ISSUE THREAD

**Issue by erickzanardo** [felangel/mocktail#77]
Mocktail could provide some default stub instances that are common use and not project specific.

A common one that I usually end up writing on every project is a VoidCallbackStub, usually to check if a onPressed callback was called on widget testing.

An implementation suggestion:

```dart
class _VoidCallbackStub {
  void onCall() {}
}

class VoidCallbackStub extends Mock implements _VoidCallbackStub {}
```

then we could use it like the following:

```dart
      final listener = VoidCallbackStub();
      await _pumpWidget(
        tester,
        CustomButton(
          label: 'label',
          onPressed: listener.onCall,
        ),
      );

      await tester.tap(find.byType(GestureDetector));
      await tester.pumpAndSettle();
   
      verify(listener.onCall).called(1);

```

Is this something worth adding to Mocktail?

**Comment by erickzanardo** [comment]
Hey, thanks for the response.

Yeah, the counter variable is something that I also used and it work perfectly, but this proposal makes it a little bit more convenient.

A separate package sounds good too! Would that be something that could be kept under this mono repo? If so I would love to do a PR including it.

Otherwise if you prefer to make it external, I could maintain it.

**Comment by felangel** [comment]
Sorry for the delayed response! I'd prefer to create a separate package (maybe https://pub.dev/packages/mocktailx would accept a PR?).

Let me know what you think 👍

**Comment by erickzanardo** [comment]
Sounds good! I will work on this on a external package, thanks @felangel !
