### ISSUE TITLE
Has support socket ? 

### ISSUE THREAD

**Issue by ProFive** [felangel/mocktail#79]
Has support socket?

**Comment by felangel** [comment]
Hi @ProFive 
Can you clarify your question? I don’t understand what you mean by support socket.

**Comment by ProFive** [comment]
Dear @felangel ,
The flutter socket 
`import 'dart:io';
import 'dart:async';

Socket socket;

void main() {
   Socket.connect("localhost", 4567).then((Socket sock) {
   socket = sock;
   socket.listen(dataHandler, 
      onError: errorHandler, 
      onDone: doneHandler, 
      cancelOnError: false);
   }).catchError((AsyncError e) {
      print("Unable to connect: $e");
   });
   //Connect standard in to the socket 
   stdin.listen((data) => socket.write(new String.fromCharCodes(data).trim() + '\n'));
}

void dataHandler(data){
   print(new String.fromCharCodes(data).trim());
}

void errorHandler(error, StackTrace trace){
   print(error);
}

void doneHandler(){
   socket.destroy();
}
`
When connect to socket succeed then we can write more cmd into the socket and listen to data response.
