### ISSUE TITLE
type 'Null' is not a subtype of type 'Future<Either<FailureInterface, bool>>'

### ISSUE THREAD

**Issue by cezar-pereira** [felangel/mocktail#90]
**Test:** 

    class RemoveEmployeeMock extends Mock implements RemoveEmployeeInterface {}
 
    void main() {
      late final RemoveEmployeeInterface useCase;
      setUpAll(() {
        useCase = RemoveEmployeeMock();
      });
    test('Should return TRUE when remove employee', () async {
      when(() => useCase.call(id: 'id'))
          .thenAnswer((_) async => const Right(true));

    var result = await useCase.call(id: '');
    expect(result, const Right(true));
      });
    }

**RemoveEmployeeInterface:** 

    abstract class RemoveEmployeeInterface {
      Future<Either<FailureInterface, bool>> call({required String id});
    }
    
    class RemoveEmployee implements RemoveEmployeeInterface {
      final EmployeeRepositoryInterface repository;
      RemoveEmployee({required this.repository});
    
      @override
      Future<Either<FailureInterface, bool>> call({required String id}) {
        return repository.removeEmployee(id: id);
      }
    }

**Comment by felangel** [comment]
Hi @cezar-pereira 👋 
Thanks for opening an issue!

I believe the problem is in your stub you are only stubbing the useCase for the specific `id: 'id'` but then you later call the useCase with `id: ''`. You should be able to adjust your test like:

```dart
class RemoveEmployeeMock extends Mock implements RemoveEmployeeInterface {}

void main() {
  late final RemoveEmployeeInterface useCase;
  setUpAll(() {
    useCase = RemoveEmployeeMock();
  });

  test('Should return TRUE when remove employee', () async {
    when(() => useCase.call(id: any())).thenAnswer((_) async => const Right(true));

    final result = await useCase.call(id: '');
    expect(result, const Right(true));
    verify(() => useCase.call(id: '')).called(1);
  });
}
```

Hope that helps 👍

**Comment by cezar-pereira** [comment]
Hi Thank you very, very, very much!!

**Comment by cezar-pereira** [comment]
Changed   when(() => useCase.call(id: 'id')).thenAnswer((_) async => const Right(true));
to
when(() => useCase.call(id: '')).thenAnswer((_) async => const Right(true));

Problem fixed.
