### ISSUE TITLE
Support for generic type matching

### ISSUE THREAD

**Issue by mtwichel** [felangel/mocktail#95]
**Is your feature request related to a problem? Please describe.**

I am trying to make an object that supports the following type of method:
```dart
class Foo {
    T get<T>() {
        // implementation
    }
}
```

and I was hoping to mock it like so

```dart
class MockFoo extends Mock implements Foo { }

test('get returns proper values', () {
    final foo = MockFoo();
    when(() => foo.get<int>()).thenReturn(5);
    when(() => foo.get<String>()).thenReturn('test');

    expect(foo.get<int>(), 5);
    expect(foo.get<String>(), 'test');
});
```

Unfortunately, this throws the following error:
`_TypeError (type 'String' is not a subtype of type 'int')`

**Describe the solution you'd like**
It would be awesome if when mocking generics, Mocktail would be able to tell the difference between these two methods so the above test would pass.

**Describe alternatives you've considered**
I really don't think I could have an alternative solution without substantially changing how the object works. 

**Additional context**
I believe the `_useMatchedInvocationIfSet` method (in `lib/src/_is_invocation.dart`, line `102`) may be where a check that the invocation supports not only the same arguments but the same generic type definitions as well. In the passed invocation object, there is a field called `_typeArguments` that contains a list of the generic types passed into the invocation. I think we could add this as criteria for matching invocation and it would support this feature.

Thanks in advance! As always, I'm super grateful for everything you and this package bring to the Dart ecosystem, and I'm happy to help with a PR if you think this is worthwhile!

**Comment by mtwichel** [comment]
Only now realizing this is probably a duplicate of #66 and fixed by #67. If it is I can close it and I'll drop a thumbs up on the PR :)

**Comment by felangel** [comment]
Hey @mtwichel yup it’s a duplicate and I’ll try to get that merged and published in the next few days 👍

**Comment by mtwichel** [comment]
Thanks as always @felangel 🎉🎉

**Comment by c-lamont** [comment]
@felangel @mtwichel I think the prs 66/67 were referring to fixing the verify issue:
`final result = verify(() => stub.someMethodWithTypeArgs<SomeType>());`

But I am still having the issue with when/return as described in the original question:
`when(() => foo.get<int>()).thenReturn(5);`

Could either of you confirm whether the when/return generic been implemented or not?

**Comment by felangel** [comment]
> @felangel @mtwichel I think the prs 66/67 were referring to fixing the verify issue: `final result = verify(() => stub.someMethodWithTypeArgs<SomeType>());`
> 
> But I am still having the issue with when/return as described in the original question: `when(() => foo.get<int>()).thenReturn(5);`
> 
> Could either of you confirm whether the when/return generic has been implemented or not?

Can you provide a link to a minimal reproduction sample? I'm happy to take a look 👍

**Comment by c-lamont** [comment]
So making a simplified project proved that Mocktail does handle generics correctly. From that I have managed to solve my issue 🎉 
Thanks for the quick response and making this great package 👍
